name: Train LSTM on Azure ML

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main
  pull_request:
    branches:
      - main

jobs:
  train-lstm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Azure ML SDK
        run: pip install azureml-sdk azureml-core

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure ML Training Pipeline
        run: python pipeline.py
